### ISSUE TITLE
Static class properties and eslint

### ISSUE THREAD

**Issue by aksel** [artboost/router5-react-redux#1]
Static class properties are caught by the linter. E.g.
```
class Foo extends React.Component {
  static propTypes = { bar: PropTypes.string }; <--- Eslint parsing error: Unexpected token =
}
```
I can't for the life of me figure this out.

Something goes wrong in the linter configuration. It seems to be missing the [transform-class-properties](https://babeljs.io/docs/plugins/transform-class-properties/) plugin, but it should be part of the [babel preset I'm using](https://www.npmjs.com/package/babel-preset-react-app)

This is a minor annoyance, but any help is greatly appreciated.

**Comment by aksel** [comment]
Almost a year later, encountered this bug again somewhere else.

[This fixes the issue](https://github.com/babel/babel-eslint/issues/312#issuecomment-317688758)

**Comment by sumitngupta** [comment]
:+1: just hit the same issue. Adding the babel-eslint package and setting as the parser in the eslintrc worked.
